
./SDP_download.sh 'IIT'
./SDP_download.sh 'autosomalXShredder'       
./SDP_download.sh 'pgSIT' 
./SDP_download.sh 'SIT'
./SDP_download.sh 'SplitDrive-DsX'    
./SDP_download.sh 'SplitDrive-YG'
./SDP_download.sh 'fsRIDL'
./SDP_download.sh 'CRISPR-YG' 
./SDP_download.sh 'CRISPR-DsX' 
